### ISSUE TITLE
Is it possible to target Core CLR?

### ISSUE THREAD

**Issue by zam6ak** [damianh/LibLog#35] opened 2015-02-14 19:38 UTC
Hi

I am attempting to use LibLog with new preview of VS 2015.
I 'dropped' LibLog.cs into new (poorly named) "ASP NET 5 Class Library" project ([which will be renamed](http://stackoverflow.com/a/28036015) to ".NET Class Library (Cross-platform)" and have attempted to target Core CLR...

After a number of added references, I am left with 2 unresolved references and 1 error.
Below is my project.json file as a reference and 3 compiler errors I have encountered....
1. Is it even feasible targeting much restrictive "asnetcore50" ?
2. If yes, any hints on how I may go about resolving the errors?

Thanks
z.

errors

```
    Error   CS0246  The type or namespace name 'StackFrame' could not be found (are you missing a using directive or an assembly reference?)    AspNet5ClassLibrary1.ASP.NET Core 5.0   LibLog.cs   379
    Error   CS0117  'Delegate' does not contain a definition for 'CreateDelegate'   AspNet5ClassLibrary1.ASP.NET Core 5.0   LibLog.cs   1910
    Error   CS1061  'Type' does not contain a definition for 'Assembly' and no extension method 'Assembly' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)   AspNet5ClassLibrary1.ASP.NET Core 5.0   LibLog.cs   1919
```

project.json

``` javascript
{
    "version": "1.0.0-*",
    "dependencies": {

    },

    "frameworks": {
        "net45": {
            "dependencies": {
            }
        },
        "aspnet50": {
            "dependencies": {
            }
        },
        "aspnetcore50": {
            "dependencies": {
                "System.Runtime": "4.0.20-beta-*",
                "System.Runtime.Extensions": "4.0.10-beta-*",
                "System.Collections": "4.0.10-beta-*",
                "System.Console": "4.0.0-beta-*",
                "System.Diagnostics.Process": "4.0.0-beta-*",
                "System.Diagnostics.Tools": "4.0.0-beta-*",
                "System.Diagnostics.Contracts": "4.0.0-beta-*",
                "System.Diagnostics.Debug": "4.0.0-beta-*",
                "System.Diagnostics.TraceSource": "4.0.0-beta-*",
                "System.Diagnostics.FileVersionInfo": "4.0.0-beta-*",
                "System.Linq": "4.0.0-beta-*",
                "System.Linq.Expressions": "4.0.0-beta-*",
                "System.Globalization": "4.0.10-beta-*",
                "System.Text.RegularExpressions": "4.0.10-beta-*",
                "System.Dynamic.Runtime": "4.0.0-beta-*",
                "System.Reflection": "4.0.10-beta-*",
                "System.Reflection.Primitives": "4.0.0-beta-*",
                "System.Reflection.TypeExtensions": "4.0.0-beta-*",
                "System.Reflection.Extensions": "4.0.0-beta-*"
            }
        }
    }
}
```

**Comment by damianh** [comment] 2015-02-14 21:31
I haven't had any joy with stability regarding VS2015 etc so I haven't
really looked at it. To be honest, I don't even know if the approach LibLog
takes - it depends on code transform to adjust the namespaces, reflection
for invoking - will even work.

Since Build is happening end of April at which I expect that's when
everything gets released, I'll take a look at this around then.

Cheers.

**Comment by damianh** [comment] 2015-03-28 19:42
Well CTP 6 borked my stuff as well. Going to wait until next release, which won't be too far away given how close //build is.

**Comment by damianh** [comment] 2015-05-03 21:10
Well the good news is that LibLog (using `LIBLOG_PORTABLE`) _compiles_ when targeting `dnxcore50`. https://github.com/damianh/LimitsMiddleware/commit/45891d4def136c823aa6c648e09edef704d58dc9 I don't yet know fully works yet.

I still don't know how to do a namespace transform yet.

**Comment by damianh** [comment] 2015-10-29 11:37
Just an update, am still waiting for the dust to settle on CoreClr / dnx etc.

**Comment by JakeGinnivan** [comment] 2015-12-24 02:34
I just had a look into this but couldn't get it working. NuGet 3.3 released the new contentFiles feature which supports transforms and such. Spec for the feature at https://github.com/NuGet/Home/wiki/%5BSpec%5D-Content-v2-for-project.json

Hopefully @yishaigalatzer can give us some insights.

**Comment by yishaigalatzer** [comment] 2015-12-24 05:56
Ah, I see. Dnx doesn't yet support contentfiles, it should in the next version.

@davidfowler

**Comment by JakeGinnivan** [comment] 2015-12-24 05:59
FYI I also couldn't actually put contentFiles into the nuspec and keep the build the same. 

See https://github.com/JakeGinnivan/LibLog/tree/ContentFiles

**Comment by damianh** [comment] 2016-03-29 15:22
Waiting for RC2 before attempting this...

**Comment by ghuntley** [comment] 2016-05-17 06:50
RC2 is out!

**Comment by damianh** [comment] 2016-05-18 19:10
Time to have a look so!

Hope existing libs can just compile fine (probably with the PCL compilation
symbol)

**Comment by damianh** [comment] 2016-05-27 09:50
Well it seems all is not calm in .net core world. Will be waiting a bit longer so...

**Comment by dls314** [comment] 2016-05-27 17:15
Not calm from yesterday's slack storm?

**Comment by damianh** [comment] 2016-05-27 20:41
Not at all, no.

**Comment by RichiCoder1** [comment] 2016-06-14 22:32
For anyone who might be curious, this worked perfectly for me near as I can tell:
```json
    "netstandard1.5": {
      "dependencies": {
        "System.Diagnostics.StackTrace": "4.0.1-rc2-*",
        "System.Runtime.InteropServices.RuntimeInformation": "4.0.0-rc2-*",
        "Microsoft.CSharp": "4.0.1-rc2-*",
        "System.Dynamic.Runtime": "4.0.11-rc2-*",
        "System.Diagnostics.Tools": "4.0.1-rc2-*",
        "System.Linq.Expressions": "4.0.11-rc2-*",
        "System.Text.RegularExpressions": "4.0.12-rc2-*"
      },
      "imports": "dnxcore5",
      "buildOptions": {
        "define": [ "LIBLOG_PORTABLE" ]
      }
    }
```

**Comment by cwe1ss** [comment] 2016-07-12 19:56
v1.0 of .NET Core would be out :)

**Comment by JakeGinnivan** [comment] 2016-07-13 06:25
I think the problem is not compiling it, it's how to include liblog via project.json because it doesn't support content packages?

**Comment by aggieben** [comment] 2016-07-27 03:48
@JakeGinnivan yes, that's what I'm trying to figure out.  What would be ideal is if there were a way to get the path of the NuGet package on the filesystem and then use it directly in the `preprocess` entry in `project.json`:

```
"preprocess": {
  "include": [
    "%nuget:PathToLibLog%/content/**/LibLog.cs.pp"
  ]
}
```

**Comment by damianh** [comment] 2017-01-24 22:03
I believe @adamralph got it working with [Blunt](https://github.com/adamralph/blunt). 

Just going to wait for the tooling and churn to settle lads.

**Comment by adamralph** [comment] 2017-01-24 22:14
I can probably whip up a quick PR soon which shows how to package it. Aftee that, the bulk of the work will probably be to get it to compile for a netstandard version. You.might to have scatter a few `#if`'s around...

**Comment by damianh** [comment] 2017-01-24 22:16
Thanks for the offer lad, but hold off anyway. I'll get on this when
tooling settles.

**Comment by adamralph** [comment] 2017-01-28 09:57
No worries.

Actually, there's not much to it: https://github.com/adamralph/liteguard/blob/5d84889bd0123900b952f1967760b2c335ae5425/src/LiteGuard.Source.nuspec#L35-L44

Couple of things to note:

- for the new world (`project.json` and 2017 `.csproj`) the files need to appear in both the `contentFiles` *and* `files` elements in the `.nuspec`. Note the relative construction of paths in each element <img src="https://cloud.githubusercontent.com/assets/677704/22395744/13d142aa-e547-11e6-8a7d-8f107e339e86.png" width="32px" />
- For LiteGuard, I'm outputting the `net35` file to both `content` and `contentFiles`, allowing the package to work both in the old world (`packages.config`) and the new world <img src="https://cloud.githubusercontent.com/assets/677704/22395759/c7a16e2c-e547-11e6-81c7-32df0dd49f6c.png" width="32px" />

**Comment by tofutim** [comment] 2017-01-28 16:00
I have been using my PR LibLog successfully with no issues.

**Comment by damianh** [comment] 2017-03-17 12:20
Closing as duplicate of #124 #125

**Closed by damianh** 2017-03-17 12:20 UTC
Labels: breaking-change, enhancement
