### ISSUE TITLE
NLog structured logging not working with version 4.2.6

### ISSUE THREAD

**Issue by santiagoIT** [damianh/LibLog#259] opened 2019-08-30 20:56 UTC
I am using NLog version 4.6.7. This version supports structured logging.
Our application targets .NET 4.5.2.

Unfortunately we cannot target .NET Core just yet.

That means that we have to use the 4.x versions, as stated in the LibLog project description.

I am using Seq as a viewer.

When using LibLog 4.2.6 the logs just contain the flat formatted string.

I did a simple console project targeting .NET Core. Here I used LibLog 5.0.6 and the logging events now display the structured logging properties.

Can structured logging support for NLog please be added to version 4?

**Comment by snakefoot** [comment] 2019-08-30 22:51
Duplicate of #239

https://github.com/snakefoot/LibLog/blob/1362d476238d405eba01f11bba28e6a4d858773c/src/LibLog/LibLog.cs (Choose "Raw" for copy-paste)

And just update your own copy of LibLog.cs.

**Comment by santiagoIT** [comment] 2019-08-31 16:11
@snakefoot Thanks, that did the trick!
Does a pull request exist for those changes? Will they be merged into this repository?

**Comment by snakefoot** [comment] 2019-08-31 20:25
@santiagoIT You can find the PullRequest here: #145.

It has been merged and is included in LibLog ver. 5.0.4 (Notice a performance bug is introduced with ver. 5.0.5 and newer that hopefully will be fixed when #233 is merged)

**Comment by damianh** [comment] 2019-12-04 23:01
5.0.8 has just been released https://www.nuget.org/packages/LibLog/5.0.8

**Closed** 2019-12-04 23:01 UTC
