### ISSUE TITLE
NLog's Logical contexts (NestedDiagnosticsLogicalContext and MappedDiagnosticsLogicalContext) are not being set.

### ISSUE THREAD

**Issue by AlexeyRokhin** [damianh/LibLog#228] opened 2019-03-01 08:40 UTC
`NLogLogProvider.GetOpenNdcMethod` and `NLogLogProvider.GetOpenMdcMethod` always use methods of classes `NestedDiagnosticsContext` and `MappedDiagnosticsContext` instead of corresponding methods of `NestedDiagnosticsLogicalContext` and `MappedDiagnosticsLogicalContext` even if `Logical` types exists in NLog's assembly.

This happens because of incorrect detection of `PushObject` method of `NestedDiagnosticsLogicalContext`. There is no method with name `PushObject` in `NestedDiagnosticsLogicalContext` (at least in NLog 4.5.11). There is a generic method `Push`. Moreover, this method is not required in `NLogLogProvider.GetOpenMdcMethod` because it requires `MappedDiagnosticsLogicalContext.SetScoped`.

**Comment by snakefoot** [comment] 2019-03-02 15:02
@AlexeyRokhin It is working as intended. NLog 4.5 (or older) doesn't handle custom objects very well when doing transfer of state from one AppDomain to another. This is fixed with NLog 4.6

Also changing from MDC to MDLC is a breaking change. If having multiple components using LibLog then it is best if they all switch to MDLC at the same time. This

This is why I have made it dependent on upgrading to NLog 4.6. In case the application having sub-components built with an old version LibLog. Then the application can just keep using NLog 4.5 and all sub-components will work the same.

**Comment by damianh** [comment] 2019-03-03 11:38
I'm going to take @snakefoot advice on this (as they are a NLog contributor) and mark it as 'invalid' (bascialy `by-design`). Thanks for reporting too.

**Closed by damianh** 2019-03-03 11:38 UTC

**Comment by damianh** [comment] 2019-03-03 11:42
@snakefoot Thanks again for responding; deeply appreciated.

**Comment by snakefoot** [comment] 2019-03-22 18:51
@AlexeyRokhin NLog 4.6 has now been released: https://www.nuget.org/packages/NLog.

Created #233 that updates the LibLog Test project.

So just update to NLog 4.6 and all your worries are over
