### ISSUE TITLE
CS1573 - Parameter 'destructure' has no matching param tag in the XML comment for 'ILogProvider.OpenMappedContext

### ISSUE THREAD

**Issue by Master-Inspire** [damianh/LibLog#171] opened 2018-07-03 13:44 UTC
Hello, 

I just installed LibLog `5.0.2` via NuGet, and got this `CS1573` warning.

> CS1573	Parameter `destructure` has no matching param tag in the XML comment for 'ILogProvider.OpenMappedContext(string, object, bool)' (but other parameters do)

https://github.com/damianh/LibLog/blob/f97a6803c917afb36b63b8eeb6bcb5da1de03917/src/LibLog/ILogProvider.cs#L37

I have set `TreatWarningsAsErrors` to `true` (so build will fail), and I don't want to ignore this type of warning.

**Comment by flytzen** [comment] 2018-09-01 21:15
This is probably caused by #174  (and will most likely be fixed by #177)

**Comment by snakefoot** [comment] 2018-11-12 23:50
It has been resolved with #173. The fix will be included in LibLog ver. 5.0.3

**Comment by snakefoot** [comment] 2018-11-12 23:50
@damianh It has been resolved with #173. The fix will be included in LibLog ver. 5.0.3

**Closed** 2018-11-13 09:47 UTC
